/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.FuncionariosDAO;
import Model.Funcionarios;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marce
 */
public class FuncionariosView extends javax.swing.JInternalFrame {

    public void listTable() {
        FuncionariosDAO dao = new FuncionariosDAO();
        List<Funcionarios> lista = dao.listarFuncionarios();

        DefaultTableModel dados = (DefaultTableModel) tbFuncionarios.getModel();
        dados.setNumRows(0);
        for (Funcionarios c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getFuncao(),
                c.getAcesso()
            });
        }
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public boolean Senha() {
        if (tfSenha.getText().toString().equals(tfRepSenha.getText().toString())
                && !tfSenha.equals("")) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Creates new form Funcionarios
     */
    public FuncionariosView() {
        initComponents();
        setTitle("Funcionários");
        listTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        abaCadastrarFuncio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfFuncao = new javax.swing.JTextField();
        lbIE = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfCpf = new javax.swing.JFormattedTextField();
        cnpj = new javax.swing.JLabel();
        tfRg = new javax.swing.JFormattedTextField();
        cnpj1 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        cnpj2 = new javax.swing.JLabel();
        cbNivel = new javax.swing.JComboBox<>();
        cnpj3 = new javax.swing.JLabel();
        tfRepSenha = new javax.swing.JPasswordField();
        tfLogin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbItemPesquisa = new javax.swing.JComboBox<>();
        tfClientePesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFuncionarios = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Funcionários");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        abaCadastrarFuncio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");

        tfNome.setBackground(new java.awt.Color(255, 255, 255));
        tfNome.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Celular:");

        tfEmail.setBackground(new java.awt.Color(255, 255, 255));
        tfEmail.setForeground(new java.awt.Color(0, 0, 0));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Email:");

        tfFuncao.setBackground(new java.awt.Color(255, 255, 255));
        tfFuncao.setForeground(new java.awt.Color(0, 0, 0));

        lbIE.setBackground(new java.awt.Color(0, 0, 0));
        lbIE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbIE.setForeground(new java.awt.Color(0, 0, 0));
        lbIE.setText("Função:");

        cpf.setBackground(new java.awt.Color(0, 0, 0));
        cpf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cpf.setForeground(new java.awt.Color(0, 0, 0));
        cpf.setText("CPF:");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Endereço:");

        tfEndereco.setBackground(new java.awt.Color(255, 255, 255));
        tfEndereco.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Número:");

        tfNumero.setBackground(new java.awt.Color(255, 255, 255));
        tfNumero.setForeground(new java.awt.Color(0, 0, 0));

        tfComplemento.setBackground(new java.awt.Color(255, 255, 255));
        tfComplemento.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Complemento:");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Bairro:");

        tfBairro.setBackground(new java.awt.Color(255, 255, 255));
        tfBairro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cidade:");

        tfCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfCidade.setForeground(new java.awt.Color(0, 0, 0));

        tfCelular.setBackground(new java.awt.Color(255, 255, 255));
        tfCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCelular.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID:");

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(255, 255, 255));
        tfId.setForeground(new java.awt.Color(0, 0, 0));

        tfCpf.setBackground(new java.awt.Color(255, 255, 255));
        tfCpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cnpj.setBackground(new java.awt.Color(0, 0, 0));
        cnpj.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cnpj.setForeground(new java.awt.Color(0, 0, 0));
        cnpj.setText("RG:");

        tfRg.setBackground(new java.awt.Color(255, 255, 255));
        tfRg.setForeground(new java.awt.Color(0, 0, 0));
        try {
            tfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cnpj1.setBackground(new java.awt.Color(0, 0, 0));
        cnpj1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cnpj1.setForeground(new java.awt.Color(0, 0, 0));
        cnpj1.setText("Senha:");

        tfSenha.setBackground(new java.awt.Color(255, 255, 255));
        tfSenha.setForeground(new java.awt.Color(0, 0, 0));

        cnpj2.setBackground(new java.awt.Color(0, 0, 0));
        cnpj2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cnpj2.setForeground(new java.awt.Color(0, 0, 0));
        cnpj2.setText("Nível de acesso:");

        cbNivel.setBackground(new java.awt.Color(255, 255, 255));
        cbNivel.setForeground(new java.awt.Color(0, 0, 0));
        cbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Administrador" }));

        cnpj3.setBackground(new java.awt.Color(0, 0, 0));
        cnpj3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cnpj3.setForeground(new java.awt.Color(0, 0, 0));
        cnpj3.setText("Repita a senha:");

        tfRepSenha.setBackground(new java.awt.Color(255, 255, 255));
        tfRepSenha.setForeground(new java.awt.Color(0, 0, 0));

        tfLogin.setBackground(new java.awt.Color(255, 255, 255));
        tfLogin.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Login:");

        javax.swing.GroupLayout abaCadastrarFuncioLayout = new javax.swing.GroupLayout(abaCadastrarFuncio);
        abaCadastrarFuncio.setLayout(abaCadastrarFuncioLayout);
        abaCadastrarFuncioLayout.setHorizontalGroup(
            abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumero))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastrarFuncioLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastrarFuncioLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfComplemento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastrarFuncioLayout.createSequentialGroup()
                        .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                                .addComponent(cnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                                .addComponent(cnpj1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cnpj3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfRepSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cnpj2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                                .addComponent(cpf)
                                .addGap(18, 18, 18)
                                .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbIE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFuncao))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastrarFuncioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEmail))
                            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );

        abaCadastrarFuncioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfRepSenha, tfSenha});

        abaCadastrarFuncioLayout.setVerticalGroup(
            abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrarFuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf)
                    .addComponent(tfCpf)
                    .addComponent(cnpj)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpj1)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpj2)
                    .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpj3)
                    .addComponent(tfRepSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastrarFuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Cadastrar", abaCadastrarFuncio);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Pesquisar por:");

        cbItemPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        cbItemPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbItemPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        cbItemPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome", "Função", "Acesso" }));
        cbItemPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemPesquisaItemStateChanged(evt);
            }
        });

        tfClientePesquisa.setBackground(new java.awt.Color(255, 255, 255));
        tfClientePesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfClientePesquisa.setForeground(new java.awt.Color(0, 0, 0));
        tfClientePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClientePesquisaActionPerformed(evt);
            }
        });
        tfClientePesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfClientePesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClientePesquisaKeyReleased(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tbFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        tbFuncionarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tbFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        tbFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "Função", "Acesso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFuncionarios);
        if (tbFuncionarios.getColumnModel().getColumnCount() > 0) {
            tbFuncionarios.getColumnModel().getColumn(0).setMinWidth(30);
            tbFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbFuncionarios.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btPesquisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icnLupa.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbItemPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfClientePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbItemPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfClientePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jPanel5);

        btNovo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btNovo.setText("NOVO");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEditar.setText("EDITAR");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70)
                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btEditar)
                    .addComponent(btExcluir))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void cbItemPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemPesquisaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbItemPesquisaItemStateChanged

    private void tfClientePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClientePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClientePesquisaActionPerformed

    private void tfClientePesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClientePesquisaKeyPressed
        // TODO add your handling code here:

        //        ClientesDAO dao = new ClientesDAO();
        //        System.out.println("tipo: " + cbItemPesquisa.getSelectedItem().toString());
        //        String pesquisa = "'%" + tfClientePesquisa.getText() + "%'";
        //        List<Clientes> lista = dao.PesquisarClientes(cbItemPesquisa.getSelectedItem().toString(), pesquisa);
        //
        //        DefaultTableModel dados = (DefaultTableModel) tbClientes.getModel();
        //        dados.setNumRows(0);
        //       if (lista != null) {
        //            for (Clientes c : lista) {
        //                dados.addRow(new Object[]{
        //                    c.getId(),
        //                    c.getNome(),
        //                    c.getCelular(),
        //                    c.getPessoa(),
        //                    c.getCpfcnpj()
        //                });
        //            }
        //        }
    }//GEN-LAST:event_tfClientePesquisaKeyPressed

    private void tfClientePesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClientePesquisaKeyReleased
        // TODO add your handling code here:

        FuncionariosDAO dao = new FuncionariosDAO();
        System.out.println("tipo: " + cbItemPesquisa.getSelectedItem().toString());
        String pesquisa = "'%" + tfClientePesquisa.getText() + "%'";
        List<Funcionarios> lista = dao.PesquisarFuncionarios(cbItemPesquisa.getSelectedItem().toString(), pesquisa);

        DefaultTableModel dados = (DefaultTableModel) tbFuncionarios.getModel();
        dados.setNumRows(0);
        if (lista != null) {
            for (Funcionarios c : lista) {
                dados.addRow(new Object[]{
                    c.getId(),
                    c.getNome(),
                    c.getFuncao(),
                    c.getAcesso()
                });
            }
        }
    }//GEN-LAST:event_tfClientePesquisaKeyReleased

    private void tbFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncionariosMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);

        FuncionariosDAO funcionariosDAO = new FuncionariosDAO();
        Funcionarios funcionarios = new Funcionarios();

        funcionarios = (Funcionarios) funcionariosDAO.exibirFuncionario(tbFuncionarios.getValueAt(tbFuncionarios.getSelectedRow(), 0).toString());

        tfId.setText(String.valueOf(funcionarios.getId()));
        tfNome.setText(funcionarios.getNome());
        tfLogin.setText(funcionarios.getLogin());
        tfCelular.setText(funcionarios.getCelular());
        tfEmail.setText(funcionarios.getEmail());
        tfEndereco.setText(funcionarios.getEndereco());
        tfNumero.setText(String.valueOf(funcionarios.getNumero()));
        tfComplemento.setText(funcionarios.getComplemento());
        tfBairro.setText(funcionarios.getBairro());
        tfCidade.setText(funcionarios.getCidade());
        tfRg.setText(funcionarios.getRg());
        tfCpf.setText(funcionarios.getCpfcnpj());
        tfFuncao.setText(funcionarios.getFuncao());
        for (int i = 0; i <= cbNivel.getMaximumRowCount(); i++) {
            if (funcionarios.getAcesso().equals(cbNivel.getItemAt(i))) {
                cbNivel.setSelectedIndex(i);
            }
        }

    }//GEN-LAST:event_tbFuncionariosMouseClicked

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        FuncionariosDAO dao = new FuncionariosDAO();
        System.out.println("tipo: " + cbItemPesquisa.getSelectedItem().toString());
        String pesquisa = "'%" + tfClientePesquisa.getText() + "%'";
        List<Funcionarios> lista = dao.PesquisarFuncionarios(cbItemPesquisa.getSelectedItem().toString(), pesquisa);

        DefaultTableModel dados = (DefaultTableModel) tbFuncionarios.getModel();
        dados.setNumRows(0);
        if (lista != null) {
            for (Funcionarios c : lista) {
                dados.addRow(new Object[]{
                    c.getId(),
                    c.getNome(),
                    c.getFuncao(),
                    c.getAcesso()
                });
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        new util.Util().LimpaTela(abaCadastrarFuncio);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        if (Senha()) {
            Funcionarios funcionarios = new Funcionarios();
            funcionarios.setNome(tfNome.getText());
            funcionarios.setLogin(tfLogin.getText());
            funcionarios.setRg(tfRg.getText());
            funcionarios.setCpfcnpj(tfCpf.getText());
            funcionarios.setEmail(tfEmail.getText());
            funcionarios.setSenha(tfSenha.getText());
            funcionarios.setFuncao(tfFuncao.getText());
            funcionarios.setAcesso(cbNivel.getSelectedItem().toString());
            funcionarios.setCelular(tfCelular.getText());
            funcionarios.setEndereco(tfEndereco.getText());
            funcionarios.setNumero(Integer.parseInt(tfNumero.getText()));
            funcionarios.setComplemento(tfComplemento.getText());
            funcionarios.setBairro(tfBairro.getText());
            funcionarios.setCidade(tfCidade.getText());
            funcionarios.setId(Integer.parseInt(tfId.getText()));

            FuncionariosDAO funcionariosDAO = new FuncionariosDAO();
            funcionariosDAO.alterarFuncionario(funcionarios);
            listTable();

            new util.Util().LimpaTela(abaCadastrarFuncio);
        } else {
            JOptionPane.showMessageDialog(null, "Senhas vazias ou não coincidem.");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:

        if (Senha()) {
            Funcionarios funcionarios = new Funcionarios();
            funcionarios.setNome(tfNome.getText());
            funcionarios.setLogin(tfLogin.getText());
            funcionarios.setRg(tfRg.getText());
            funcionarios.setCpfcnpj(tfCpf.getText());
            funcionarios.setEmail(tfEmail.getText());
            funcionarios.setSenha(tfSenha.getText());
            funcionarios.setFuncao(tfFuncao.getText());
            funcionarios.setAcesso(cbNivel.getSelectedItem().toString());
            funcionarios.setCelular(tfCelular.getText());
            funcionarios.setEndereco(tfEndereco.getText());
            funcionarios.setNumero(Integer.parseInt(tfNumero.getText()));
            funcionarios.setComplemento(tfComplemento.getText());
            funcionarios.setBairro(tfBairro.getText());
            funcionarios.setCidade(tfCidade.getText());

            FuncionariosDAO funcionariosDAO = new FuncionariosDAO();
            funcionariosDAO.cadastrarFuncionario(funcionarios);
            listTable();

            new util.Util().LimpaTela(abaCadastrarFuncio);
        } else {
            JOptionPane.showMessageDialog(null, "Senhas vazias ou não coincidem.");
        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        Funcionarios funcionarios = new Funcionarios();
        funcionarios.setId(Integer.parseInt(tfId.getText()));

        FuncionariosDAO funcionariosDAO = new FuncionariosDAO();
        funcionariosDAO.excluirFuncionario(funcionarios);
        listTable();
        new util.Util().LimpaTela(abaCadastrarFuncio);
    }//GEN-LAST:event_btExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastrarFuncio;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbItemPesquisa;
    private javax.swing.JComboBox<String> cbNivel;
    private javax.swing.JLabel cnpj;
    private javax.swing.JLabel cnpj1;
    private javax.swing.JLabel cnpj2;
    private javax.swing.JLabel cnpj3;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbIE;
    private javax.swing.JTable tbFuncionarios;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfClientePesquisa;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfFuncao;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JPasswordField tfRepSenha;
    private javax.swing.JFormattedTextField tfRg;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables

}
