/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ClientesDAO;
import DAO.ItemVendaDAO;
import DAO.VendasDAO;
import Model.Clientes;
import Model.ItensVenda;
import Model.Produtos;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marce
 */
public class PagamentosView extends javax.swing.JFrame {

    double pDinheiro, pCredito, pDebito, pCheque, pVale, troco, total, totalPg;
    DecimalFormat df = new DecimalFormat("0.00");
    DefaultTableModel carrinho;
    List<Produtos> itens = new ArrayList<>();

    public PagamentosView() {
        initComponents();

    }

    public void finalizar() {
        
        //ultima venda realizada
        VendasDAO daoV = new VendasDAO();
        int idVenda = daoV.ultimaVenda();
        
        for(int i = 0; i<carrinho.getRowCount();i++){
            
            ItensVenda item = new ItensVenda();
            item.setVenda(idVenda);
            item.setProduto(itens.get(i));
            item.setQtd(Integer.parseInt(carrinho.getValueAt(i, 2).toString()));
            item.setTotal(Double.parseDouble(carrinho.getValueAt(i, 4).toString().replaceAll(",", ".")));
            
            ItemVendaDAO daoI = new ItemVendaDAO();
            daoI.cadastraItem(item);
        }
        
        if (!tfDinheiro.getText().equals("")) {
            pDinheiro = Double.parseDouble(tfDinheiro.getText().replaceAll(",", "."));
        }
        if (!tfCredito.getText().equals("")) {
            pCredito = Double.parseDouble(tfCredito.getText().replaceAll(",", "."));
        }
        if (!tfDebito.getText().equals("")) {
            pDebito = Double.parseDouble(tfDebito.getText().replaceAll(",", "."));
        }
        if (!tfCheque.getText().equals("")) {
            pCheque = Double.parseDouble(tfCheque.getText().replaceAll(",", "."));
        }
        if (!tfVale.getText().equals("")) {
            pVale = Double.parseDouble(tfVale.getText().replaceAll(",", "."));
        }

        totalPg = pDinheiro + pCredito + pDebito + pCheque + pVale;

        if (total > totalPg) {
            JOptionPane.showMessageDialog(null, "Pagamento incompleto.");
        } else {
            troco = totalPg - total;
//            JOptionPane.showMessageDialog(null, "Troco: R$" + String.valueOf(df.format(troco)).replaceAll("\\.", ","));
            PDVView pdv = new PDVView();
//            pdv.troco(troco);
            PDVView.troco = troco;
            dispose();
        }

    }

    public void Pessoa(String pessoa) throws ParseException {
        switch (pessoa) {
            case "Física":
                rbFisica.setSelected(true);
                rbJuridica.setSelected(false);
                lbCpf.setText("CPF:");
                tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                        new javax.swing.text.MaskFormatter("###.###.###-##")));
                break;
            case "Jurídica":
                rbFisica.setSelected(false);
                rbJuridica.setSelected(true);
                lbCpf.setText("CNPJ:");
                tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                        new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pessoa = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbCpf = new javax.swing.JLabel();
        btPesquisarCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfCliente = new javax.swing.JTextField();
        tfCpf = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        rbFisica = new javax.swing.JRadioButton();
        rbJuridica = new javax.swing.JRadioButton();
        tfDebito = new javax.swing.JTextField();
        tfCheque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDinheiro = new javax.swing.JTextField();
        tfVale = new javax.swing.JTextField();
        btFinalizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCredito = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pagamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbCpf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbCpf.setText("CPF/CNPJ:");

        btPesquisarCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icnLupa.png"))); // NOI18N
        btPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarClienteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("NOME:");

        tfCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        tfCpf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCpfKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("PESSOA:");

        pessoa.add(rbFisica);
        rbFisica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rbFisica.setText("Física");
        rbFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFisicaActionPerformed(evt);
            }
        });

        pessoa.add(rbJuridica);
        rbJuridica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rbJuridica.setText("Jurídica");
        rbJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisarCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbJuridica)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rbFisica)
                    .addComponent(rbJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCpf)
                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        tfDebito.setBackground(new java.awt.Color(255, 255, 255));
        tfDebito.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfDebito.setForeground(new java.awt.Color(0, 0, 0));
        tfDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDebitoKeyPressed(evt);
            }
        });

        tfCheque.setBackground(new java.awt.Color(255, 255, 255));
        tfCheque.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfCheque.setForeground(new java.awt.Color(0, 0, 0));
        tfCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChequeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("F1 - DINHEIRO:");

        tfDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        tfDinheiro.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfDinheiro.setForeground(new java.awt.Color(0, 0, 0));
        tfDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDinheiroActionPerformed(evt);
            }
        });
        tfDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDinheiroKeyPressed(evt);
            }
        });

        tfVale.setBackground(new java.awt.Color(255, 255, 255));
        tfVale.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfVale.setForeground(new java.awt.Color(0, 0, 0));
        tfVale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfValeKeyPressed(evt);
            }
        });

        btFinalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btFinalizar.setText("FINALIZAR");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("F2 - CARTÃO CRÉDITO:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("F3 - CARTÃO DÉBITO:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("F4 - CHEQUE:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("F5 - VALE:");

        tfCredito.setBackground(new java.awt.Color(255, 255, 255));
        tfCredito.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfCredito.setForeground(new java.awt.Color(0, 0, 0));
        tfCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCreditoKeyPressed(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("TOTAL:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("R$");

        lbTotal.setBackground(new java.awt.Color(255, 255, 255));
        lbTotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(255, 0, 0));
        lbTotal.setText("0,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lbTotal))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfVale, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(tfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfVale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btFinalizar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDinheiroActionPerformed

    private void btPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarClienteActionPerformed
        // TODO add your handling code here:

        ClientesDAO dao = new ClientesDAO();
        Clientes c = new Clientes();
        c = dao.exibirClienteCpf(tfCpf.getText());

        tfCliente.setText(c.getNome());

    }//GEN-LAST:event_btPesquisarClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            // TODO add your handling code here:
            Pessoa("Física");
            tfDinheiro.requestFocus();
        } catch (ParseException ex) {
            Logger.getLogger(PagamentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void rbFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFisicaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Pessoa("Física");
        } catch (ParseException ex) {
            Logger.getLogger(PagamentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbFisicaActionPerformed

    private void rbJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuridicaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Pessoa("Jurídica");
        } catch (ParseException ex) {
            Logger.getLogger(PagamentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbJuridicaActionPerformed

    private void tfCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCpfKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ClientesDAO dao = new ClientesDAO();
            Clientes c = new Clientes();
            c = dao.exibirClienteCpf(tfCpf.getText());

            tfCliente.setText(c.getNome());
        }
    }//GEN-LAST:event_tfCpfKeyPressed

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void tfDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDinheiroKeyPressed
        // dinheiro
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                //dinheiro
                tfDinheiro.requestFocus();
                break;
            case KeyEvent.VK_F2:
                //crédito
                tfCredito.requestFocus();
                break;
            case KeyEvent.VK_F3:
                //débito
                tfDebito.requestFocus();
                break;
            case KeyEvent.VK_F4:
                //cheque
                tfCheque.requestFocus();
                break;
            case KeyEvent.VK_F5:
                //vale
                tfVale.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                //finalizar
                if (!tfVale.getText().equals("")) {
                    if (tfCliente.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Para vendas utilizando a opção de vale, deve-se obrigatoriamente informar um cliente");
                    } else {
                        finalizar();
                    }
                } else {
                    finalizar();
                }

                break;

        }
    }//GEN-LAST:event_tfDinheiroKeyPressed

    private void tfCreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCreditoKeyPressed
        // Crédito

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                //dinheiro
                tfDinheiro.requestFocus();
                break;
            case KeyEvent.VK_F2:
                //crédito
                tfCredito.requestFocus();
                break;
            case KeyEvent.VK_F3:
                //débito
                tfDebito.requestFocus();
                break;
            case KeyEvent.VK_F4:
                //cheque
                tfCheque.requestFocus();
                break;
            case KeyEvent.VK_F5:
                //vale
                tfVale.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                //finalizar
                break;
        }

    }//GEN-LAST:event_tfCreditoKeyPressed

    private void tfDebitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDebitoKeyPressed
        // débito

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                //dinheiro
                tfDinheiro.requestFocus();
                break;
            case KeyEvent.VK_F2:
                //crédito
                tfCredito.requestFocus();
                break;
            case KeyEvent.VK_F3:
                //débito
                tfDebito.requestFocus();
                break;
            case KeyEvent.VK_F4:
                //cheque
                tfCheque.requestFocus();
                break;
            case KeyEvent.VK_F5:
                //vale
                tfVale.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                //finalizar
                break;
        }
    }//GEN-LAST:event_tfDebitoKeyPressed

    private void tfChequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChequeKeyPressed
        // cheque

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                //dinheiro
                tfDinheiro.requestFocus();
                break;
            case KeyEvent.VK_F2:
                //crédito
                tfCredito.requestFocus();
                break;
            case KeyEvent.VK_F3:
                //débito
                tfDebito.requestFocus();
                break;
            case KeyEvent.VK_F4:
                //cheque
                tfCheque.requestFocus();
                break;
            case KeyEvent.VK_F5:
                //vale
                tfVale.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                //finalizar
                break;
        }
    }//GEN-LAST:event_tfChequeKeyPressed

    private void tfValeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValeKeyPressed
        // Vale

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                //dinheiro
                tfDinheiro.requestFocus();
                break;
            case KeyEvent.VK_F2:
                //crédito
                tfCredito.requestFocus();
                break;
            case KeyEvent.VK_F3:
                //débito
                tfDebito.requestFocus();
                break;
            case KeyEvent.VK_F4:
                //cheque
                tfCheque.requestFocus();
                break;
            case KeyEvent.VK_F5:
                //vale
                tfVale.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                //finalizar
                break;
        }
    }//GEN-LAST:event_tfValeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagamentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagamentosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btPesquisarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbCpf;
    public javax.swing.JLabel lbTotal;
    private javax.swing.ButtonGroup pessoa;
    private javax.swing.JRadioButton rbFisica;
    private javax.swing.JRadioButton rbJuridica;
    private javax.swing.JTextField tfCheque;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfCredito;
    private javax.swing.JTextField tfDebito;
    private javax.swing.JTextField tfDinheiro;
    private javax.swing.JTextField tfVale;
    // End of variables declaration//GEN-END:variables
}
