/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ProdutosDAO;
import DAO.VendasDAO;
import Model.Produtos;
import Model.Vendas;
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import util.Dados;
import util.UserLogin;

/**
 *
 * @author marce
 */
public class PDVView extends javax.swing.JFrame {

    public static double totalItem, totalVenda, troco, lucro;
//    boolean tVisi;
    int item;
    DefaultTableModel carrinho;
    DecimalFormat df = new DecimalFormat("0.00");
    List<Produtos> itens = new ArrayList<>();

    public PDVView() {
        initComponents();
    }

    public void troco(double troco) {
        PagamentosView p = new PagamentosView();
        p.dispose();
//        while (lbTroco.getText().equals("0,00")) {
//            lbTroco.setText(String.valueOf(df.format(troco)).replaceAll("\\.", ","));
//            System.out.println("troco: " + lbTroco.getText());
//            lbTroco.setVisible(true);
//        }
//        lbTroco.setText(String.valueOf(df.format(troco)).replaceAll("\\.", ","));
//        lbTroco.setVisible(true);
    }

    public void telaCheia() {
        GraphicsEnvironment graphics
                = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice device = graphics.getDefaultScreenDevice();
        device.setFullScreenWindow(this);
    }

    class hora implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            lbHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPDV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbAcesso = new javax.swing.JLabel();
        lbnumCaixa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutosVenda = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbCaixa = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbSTroco = new javax.swing.JLabel();
        lbRTroco = new javax.swing.JLabel();
        lbTroco = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfQtd = new javax.swing.JTextField();
        lbF9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbF1 = new javax.swing.JLabel();
        lbF2 = new javax.swing.JLabel();
        lbF3 = new javax.swing.JLabel();
        lbF4 = new javax.swing.JLabel();
        lbF6 = new javax.swing.JLabel();
        lbF7 = new javax.swing.JLabel();
        lbF5 = new javax.swing.JLabel();
        lbF8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        PanelPDV.setBackground(new java.awt.Color(153, 153, 255));
        PanelPDV.setForeground(new java.awt.Color(0, 0, 0));
        PanelPDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelPDVKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(81, 85, 87));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logoP.png"))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbEmpresa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmpresa.setText("Empresa");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Usuário:");

        lbUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Acesso:");

        lbAcesso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lbnumCaixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Caixa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbnumCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEmpresa)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbnumCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descrição", "Qtd", "Preço Unit", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProdutosVenda);
        if (tbProdutosVenda.getColumnModel().getColumnCount() > 0) {
            tbProdutosVenda.getColumnModel().getColumn(0).setResizable(false);
            tbProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbProdutosVenda.getColumnModel().getColumn(1).setResizable(false);
            tbProdutosVenda.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbProdutosVenda.getColumnModel().getColumn(2).setResizable(false);
            tbProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbProdutosVenda.getColumnModel().getColumn(3).setResizable(false);
            tbProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbProdutosVenda.getColumnModel().getColumn(4).setResizable(false);
            tbProdutosVenda.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        lbHora.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbHora.setForeground(new java.awt.Color(51, 51, 255));
        lbHora.setText("jLabel3");

        lbData.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbData.setForeground(new java.awt.Color(51, 51, 255));
        lbData.setText("jLabel3");

        lbCaixa.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        lbCaixa.setForeground(new java.awt.Color(255, 0, 0));
        lbCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCaixa.setText("CAIXA FECHADO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lbData)
                        .addGap(54, 54, 54))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHora)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbData)
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(lbCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("R$");

        lbTotal.setBackground(new java.awt.Color(255, 255, 255));
        lbTotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(0, 0, 204));
        lbTotal.setText("0,00");

        lbSTroco.setBackground(new java.awt.Color(255, 255, 255));
        lbSTroco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbSTroco.setForeground(new java.awt.Color(0, 0, 0));
        lbSTroco.setText("Troco:");

        lbRTroco.setBackground(new java.awt.Color(255, 255, 255));
        lbRTroco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbRTroco.setForeground(new java.awt.Color(0, 0, 204));
        lbRTroco.setText("R$");

        lbTroco.setBackground(new java.awt.Color(255, 255, 255));
        lbTroco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTroco.setForeground(new java.awt.Color(0, 0, 204));
        lbTroco.setText("0,00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSTroco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRTroco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(lbTotal)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lbRTroco)
                        .addComponent(lbSTroco)
                        .addComponent(lbTroco)))
                .addGap(28, 28, 28))
        );

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("CÓDIGO DE BARRAS:");

        tfCodigo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("QUANTIDADE:");

        tfQtd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfQtd.setText("1");
        tfQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQtdKeyPressed(evt);
            }
        });

        lbF9.setBackground(new java.awt.Color(255, 255, 255));
        lbF9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF9.setForeground(new java.awt.Color(0, 0, 0));
        lbF9.setText("F9 - Alterar Qtd.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodigo)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbF9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbF9))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        lbF1.setBackground(new java.awt.Color(255, 255, 255));
        lbF1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF1.setForeground(new java.awt.Color(0, 0, 0));
        lbF1.setText("F1 - Fechar Venda");

        lbF2.setBackground(new java.awt.Color(255, 255, 255));
        lbF2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF2.setForeground(new java.awt.Color(0, 0, 0));
        lbF2.setText("F2 - Cancelar Item");

        lbF3.setBackground(new java.awt.Color(255, 255, 255));
        lbF3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF3.setForeground(new java.awt.Color(0, 0, 0));
        lbF3.setText("F3 - Cancelar Venda");

        lbF4.setBackground(new java.awt.Color(255, 255, 255));
        lbF4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF4.setForeground(new java.awt.Color(0, 0, 0));
        lbF4.setText("F4 - Consultar Preço");

        lbF6.setBackground(new java.awt.Color(255, 255, 255));
        lbF6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF6.setForeground(new java.awt.Color(0, 0, 0));
        lbF6.setText("F5 - Sangria");

        lbF7.setBackground(new java.awt.Color(255, 255, 255));
        lbF7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF7.setForeground(new java.awt.Color(0, 0, 0));
        lbF7.setText("F6 - Abrir Caixa");

        lbF5.setBackground(new java.awt.Color(255, 255, 255));
        lbF5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF5.setForeground(new java.awt.Color(0, 0, 0));
        lbF5.setText("F7 - Fechar Caixa");
        lbF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbF5MouseClicked(evt);
            }
        });
        lbF5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbF5KeyPressed(evt);
            }
        });

        lbF8.setBackground(new java.awt.Color(255, 255, 255));
        lbF8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbF8.setForeground(new java.awt.Color(0, 0, 0));
        lbF8.setText("F8 - Sair PDV");
        lbF8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbF8MouseClicked(evt);
            }
        });
        lbF8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbF8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbF1)
                    .addComponent(lbF2)
                    .addComponent(lbF3)
                    .addComponent(lbF4))
                .addGap(100, 100, 100)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbF8)
                    .addComponent(lbF5)
                    .addComponent(lbF7)
                    .addComponent(lbF6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbF1)
                    .addComponent(lbF6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbF2)
                    .addComponent(lbF7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbF3)
                    .addComponent(lbF5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbF4)
                    .addComponent(lbF8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPDVLayout = new javax.swing.GroupLayout(PanelPDV);
        PanelPDV.setLayout(PanelPDVLayout);
        PanelPDVLayout.setHorizontalGroup(
            PanelPDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPDVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPDVLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(PanelPDVLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PanelPDVLayout.setVerticalGroup(
            PanelPDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPDVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelPDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelPDVLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setIconImage(new ImageIcon(getClass().getResource("/icons/logoP.png")).getImage());
        setTitle("ProtegoInfo");
//        telaCheia();
        this.setExtendedState(MAXIMIZED_BOTH);
        item = 0;
        try {
            lbnumCaixa.setText(Dados.Read("Caixa"));
        } catch (IOException ex) {
            Logger.getLogger(PDVView.class.getName()).log(Level.SEVERE, null, ex);
        }

        carrinho = (DefaultTableModel) tbProdutosVenda.getModel();
        lbTroco.setVisible(false);
        lbSTroco.setVisible(false);
        lbRTroco.setVisible(false);
        lbUsuario.setText(UserLogin.funcionario.getNome());
        lbAcesso.setText(UserLogin.funcionario.getAcesso());

        lbTroco.setText(String.valueOf(df.format(troco)).replaceAll("\\.", ","));
        lbF1.setText("F1 - Nova Venda");

        if (!lbTroco.getText().equals("0,00")) {
            lbTroco.setVisible(true);
            lbSTroco.setVisible(true);
            lbRTroco.setVisible(true);
            lbF1.setText("F1 - Nova Venda");
            lbCaixa.setText("CAIXA ABERTO");
            lbCaixa.setForeground(Color.GREEN);

        }

        Date dataSistema = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        lbData.setText(sdf.format(dataSistema));

        Timer timer = new Timer(1000, new PDVView.hora());
        timer.start();

        tfCodigo.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void lbF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbF5MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setExtendedState(MAXIMIZED_BOTH);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbF5MouseClicked

    private void lbF5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbF5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbF5KeyPressed

    private void tfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F1:
                if (lbF1.getText().equals("F1 - Nova Venda")) {
                    //abrir venda
                    itens.clear();
                    lbTroco.setVisible(false);
                    lbSTroco.setVisible(false);
                    lbRTroco.setVisible(false);
                    lbTroco.setText("0,00");
                    lbTotal.setText("0,00");
                    carrinho.setNumRows(0);
                    totalVenda=0;
                    lucro=0;

                } else {
                    //fechar venda
                    Vendas v = new Vendas();
                    Date dataHoraAtual = new Date();
                    String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
                    String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);

                    v.setHora(hora);
                    v.setData(data);
                    v.setTotal(totalVenda);
                    v.setLucro(lucro);
                    UserLogin userLogin = new UserLogin();
                    v.setFuncionario(userLogin.funcionario);
                    v.setStatus("NÃO FINALIZADO");

                    VendasDAO dao = new VendasDAO();
                    dao.cadastrarVenda(v);

                    PagamentosView pView = new PagamentosView();
                    pView.total = totalVenda;
                    pView.carrinho = carrinho;
                    pView.itens.clear();
                    pView.itens = itens;
                    pView.lbTotal.setText(String.valueOf(df.format(totalVenda)));
                    pView.setVisible(true);
//                    dispose();
                }

                break;
            case KeyEvent.VK_F6:
                //Abrir caixa
                lbCaixa.setText("CAIXA ABERTO");
                lbCaixa.setForeground(Color.GREEN);
                break;
            case KeyEvent.VK_F7:
                //Abrir caixa
                lbCaixa.setText("CAIXA FECHADO");
                lbCaixa.setForeground(Color.RED);
                System.out.println("itens:" + itens.toArray());
                break;
            case KeyEvent.VK_F8:
                //Voltar home
                Home home = new Home();
                home.setExtendedState(MAXIMIZED_BOTH);
                home.setVisible(true);
                dispose();
                break;
            case KeyEvent.VK_F9:
                //Aterar qtd
                tfQtd.setText("");
                tfQtd.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                //pesquisar produto pelo código
                if (!tfCodigo.getText().trim().equals("")) {
                    Produtos p = new Produtos();
                    ProdutosDAO dao = new ProdutosDAO();
                    p = dao.exibirProduto(tfCodigo.getText().trim());

                    item++;
                    itens.add(p);
                    totalItem = p.getPrecoVenda() * Integer.parseInt(tfQtd.getText());
                    lucro += (p.getLucroReal() * Integer.parseInt(tfQtd.getText()));
                    totalVenda += totalItem;
                    lbTotal.setText(String.valueOf(df.format(totalVenda)).replaceAll("\\.", ","));

                    carrinho.addRow(new Object[]{
                        String.valueOf(item),
                        p.getDescricao(),
                        String.valueOf(tfQtd.getText()),
                        String.valueOf(df.format(p.getPrecoVenda())).replaceAll("\\.", ","),
                        String.valueOf(df.format(totalItem)).replaceAll("\\.", ",")
                    });

                    lbF1.setText("F1 - Fechar Venda");
                    lbCaixa.setText("Venda Aberta");
                    lbCaixa.setForeground(Color.YELLOW);
                    tfQtd.setText("1");
                    tfCodigo.setText("");
                }
                break;

        }
    }//GEN-LAST:event_tfCodigoKeyPressed

    private void lbF8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbF8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbF8MouseClicked

    private void lbF8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbF8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbF8KeyPressed

    private void PanelPDVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelPDVKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_PanelPDVKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyPressed

    private void tfQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtdKeyPressed
        // TODO add your handling code here:

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                tfCodigo.requestFocus();
                break;
        }
    }//GEN-LAST:event_tfQtdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDVView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelPDV;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbAcesso;
    public javax.swing.JLabel lbCaixa;
    public javax.swing.JLabel lbData;
    public javax.swing.JLabel lbEmpresa;
    public javax.swing.JLabel lbF1;
    public javax.swing.JLabel lbF2;
    public javax.swing.JLabel lbF3;
    public javax.swing.JLabel lbF4;
    public javax.swing.JLabel lbF5;
    public javax.swing.JLabel lbF6;
    public javax.swing.JLabel lbF7;
    public javax.swing.JLabel lbF8;
    public javax.swing.JLabel lbF9;
    public javax.swing.JLabel lbHora;
    public javax.swing.JLabel lbRTroco;
    public javax.swing.JLabel lbSTroco;
    public javax.swing.JLabel lbTotal;
    public javax.swing.JLabel lbTroco;
    public javax.swing.JLabel lbUsuario;
    public javax.swing.JLabel lbnumCaixa;
    public javax.swing.JTable tbProdutosVenda;
    public javax.swing.JTextField tfCodigo;
    public javax.swing.JTextField tfQtd;
    // End of variables declaration//GEN-END:variables
}
