/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.FornecedoresDAO;
import DAO.ProdutosDAO;
import Model.Fornecedores;
import Model.Produtos;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marce
 */
public class ProdutosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Produtos
     */
    public ProdutosView() {
        initComponents();
    }

    private void atualizarListaFornecedores() {
        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> listaFornecedores = dao.listarFornecedores();
        cbFornecedor.removeAll();
        for (Fornecedores f : listaFornecedores) {
            cbFornecedor.addItem(f);
        }
    }

    public void listTable() {
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarFuncionarios();
        DecimalFormat df = new DecimalFormat("0.00");

        DefaultTableModel dados = (DefaultTableModel) tbProdutos.getModel();
        dados.setNumRows(0);

        for (Produtos c : lista) {
            String venda = df.format(c.getPrecoVenda());
            String estoque = c.getEstoque() + " " + c.getUnidade();
            String pVenda = "R$ " + venda.replaceAll("\\.", ",");
            dados.addRow(new Object[]{
                c.getCodBarras(),
                c.getDescricao(),
                pVenda,
                estoque,
                c.getFornecedores().getNome()
            });
        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbItemPesquisa = new javax.swing.JComboBox<>();
        tfProdutoPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        cadProdutos1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCodInterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCodBarras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfEstoqueAtual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbUnid = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfPrecoCompra = new javax.swing.JTextField();
        tfLucroPercen = new javax.swing.JTextField();
        tfLucroReal = new javax.swing.JTextField();
        tfPrecoVenda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfAddEstoque = new javax.swing.JFormattedTextField();
        cadProdutos2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tfNcm = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfIpi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfIcms = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfFrete = new javax.swing.JTextField();
        cadProdutos3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfPrecoPromo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tfPercPromo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfValorPromo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfValidadePromo = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        jButton6.setText("jButton6");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("IPI:");

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(1021, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Pesquisar por:");

        cbItemPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        cbItemPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbItemPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        cbItemPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cód. Barras", "Descrição", "Fornecedor" }));
        cbItemPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemPesquisaItemStateChanged(evt);
            }
        });

        tfProdutoPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        tfProdutoPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfProdutoPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        tfProdutoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProdutoPesquisaActionPerformed(evt);
            }
        });
        tfProdutoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfProdutoPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfProdutoPesquisaKeyReleased(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tbProdutos.setBackground(new java.awt.Color(255, 255, 255));
        tbProdutos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tbProdutos.setForeground(new java.awt.Color(0, 0, 0));
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de barras", "Descrição", "Valor de venda", "Estoque", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProdutos);
        if (tbProdutos.getColumnModel().getColumnCount() > 0) {
            tbProdutos.getColumnModel().getColumn(3).setResizable(false);
            tbProdutos.getColumnModel().getColumn(4).setResizable(false);
        }

        btPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btPesquisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icnLupa.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbItemPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProdutoPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cbItemPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfProdutoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar Produtos", jPanel3);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Código Interno:");

        tfCodInterno.setEditable(false);
        tfCodInterno.setBackground(new java.awt.Color(255, 255, 255));
        tfCodInterno.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Código de Barras:");

        tfCodBarras.setBackground(new java.awt.Color(255, 255, 255));
        tfCodBarras.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descrição:");

        tfDescricao.setBackground(new java.awt.Color(255, 255, 255));
        tfDescricao.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estoque atual:");

        tfEstoqueAtual.setEditable(false);
        tfEstoqueAtual.setBackground(new java.awt.Color(255, 255, 255));
        tfEstoqueAtual.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fornecedor:");

        cbFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        cbFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        cbFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFornecedorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Unidade:");

        cbUnid.setBackground(new java.awt.Color(255, 255, 255));
        cbUnid.setForeground(new java.awt.Color(0, 0, 0));
        cbUnid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Und", "KG", "M²", "M³" }));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Preço de Compra: R$");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Lucro em Porcentagem:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Lucro em R$:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Preço de Venda:");

        tfPrecoCompra.setBackground(new java.awt.Color(255, 255, 255));
        tfPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));

        tfLucroPercen.setBackground(new java.awt.Color(255, 255, 255));
        tfLucroPercen.setForeground(new java.awt.Color(0, 0, 0));
        tfLucroPercen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLucroPercenKeyReleased(evt);
            }
        });

        tfLucroReal.setBackground(new java.awt.Color(255, 255, 255));
        tfLucroReal.setForeground(new java.awt.Color(0, 0, 0));
        tfLucroReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLucroRealActionPerformed(evt);
            }
        });
        tfLucroReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLucroRealKeyReleased(evt);
            }
        });

        tfPrecoVenda.setBackground(new java.awt.Color(255, 255, 255));
        tfPrecoVenda.setForeground(new java.awt.Color(0, 0, 0));
        tfPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrecoVendaKeyReleased(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("%");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Adicionar estoque:");

        tfAddEstoque.setBackground(new java.awt.Color(255, 255, 255));
        tfAddEstoque.setForeground(new java.awt.Color(0, 0, 0));
        tfAddEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout cadProdutos1Layout = new javax.swing.GroupLayout(cadProdutos1);
        cadProdutos1.setLayout(cadProdutos1Layout);
        cadProdutos1Layout.setHorizontalGroup(
            cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadProdutos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadProdutos1Layout.createSequentialGroup()
                        .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadProdutos1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodBarras))
                            .addGroup(cadProdutos1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDescricao)))
                        .addGap(12, 12, 12)
                        .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEstoqueAtual)
                            .addComponent(tfAddEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cadProdutos1Layout.createSequentialGroup()
                        .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadProdutos1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLucroPercen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLucroReal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadProdutos1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUnid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadProdutos1Layout.setVerticalGroup(
            cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadProdutos1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfAddEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbUnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(tfLucroPercen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfLucroReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dados Gerais", cadProdutos1);

        cadProdutos2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("NCM:");

        tfNcm.setBackground(new java.awt.Color(255, 255, 255));
        tfNcm.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("IPI:");

        tfIpi.setBackground(new java.awt.Color(255, 255, 255));
        tfIpi.setForeground(new java.awt.Color(0, 0, 0));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ICMS:");

        tfIcms.setBackground(new java.awt.Color(255, 255, 255));
        tfIcms.setForeground(new java.awt.Color(0, 0, 0));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Frete:");

        tfFrete.setBackground(new java.awt.Color(255, 255, 255));
        tfFrete.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cadProdutos2Layout = new javax.swing.GroupLayout(cadProdutos2);
        cadProdutos2.setLayout(cadProdutos2Layout);
        cadProdutos2Layout.setHorizontalGroup(
            cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadProdutos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadProdutos2Layout.createSequentialGroup()
                        .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(10, 10, 10)
                        .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIpi, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(tfNcm))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadProdutos2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIcms, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        cadProdutos2Layout.setVerticalGroup(
            cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadProdutos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(tfFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfIpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfIcms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dados Fiscais", cadProdutos2);

        jLabel4.setText("Definir preço promocional: R$");

        jButton5.setText("Calcular valor:");

        jLabel22.setText("Definir desconto em porcentagem: ");

        jLabel3.setText("%");

        tfValorPromo.setEditable(false);

        jLabel23.setText("Validade do desconto:");

        try {
            tfValidadePromo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel24.setText("(dd/mm/aaaa)");

        jLabel25.setText("Preço de venda: R$");

        jTextField1.setEditable(false);

        jLabel26.setText("Preço Promocional: R$");

        jTextField2.setEditable(false);

        jLabel27.setText("R$");

        javax.swing.GroupLayout cadProdutos3Layout = new javax.swing.GroupLayout(cadProdutos3);
        cadProdutos3.setLayout(cadProdutos3Layout);
        cadProdutos3Layout.setHorizontalGroup(
            cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadProdutos3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(cadProdutos3Layout.createSequentialGroup()
                        .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadProdutos3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValidadePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(cadProdutos3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadProdutos3Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadProdutos3Layout.createSequentialGroup()
                                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(cadProdutos3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPrecoPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadProdutos3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPercPromo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValorPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 465, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadProdutos3Layout.setVerticalGroup(
            cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadProdutos3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPrecoPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfPercPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5)
                    .addComponent(tfValorPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfValidadePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadProdutos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Promoção", cadProdutos3);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86)
                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Produtos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(71, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        //        String pesquisa = "'%" + tfClientePesquisa.getText() + "%'";
        //        ClientesDAO dao = new ClientesDAO();
        //        System.out.println("tipo: " + cbItemPesquisa.getSelectedItem().toString());
        //        List<Clientes> lista = dao.PesquisarClientes(cbItemPesquisa.getSelectedItem().toString(), pesquisa);
        //
        //        DefaultTableModel dados = (DefaultTableModel) tbClientes.getModel();
        //        dados.setNumRows(0);
        //        if (lista != null) {
        //            for (Clientes c : lista) {
        //                dados.addRow(new Object[]{
        //                    c.getId(),
        //                    c.getNome(),
        //                    c.getCelular(),
        //                    c.getPessoa(),
        //                    c.getCpfcnpj()
        //                });
        //            }
        //        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutosMouseClicked
        // TODO add your handling code here:
//        cbFornecedor.removeAll();
//        atualizarListaFornecedores();
        jTabbedPane1.setSelectedIndex(1);

        ProdutosDAO dao = new ProdutosDAO();
        Produtos produto = new Produtos();
        Fornecedores fornecedor = new Fornecedores();
        FornecedoresDAO fDAO = new FornecedoresDAO();
        produto = dao.exibirProduto(tbProdutos.getValueAt(tbProdutos.getSelectedRow(), 0).toString());

        tfCodInterno.setText(String.valueOf(produto.getId()));
        tfCodBarras.setText(produto.getCodBarras());
        tfDescricao.setText(produto.getDescricao());
        tfEstoqueAtual.setText(String.valueOf(produto.getEstoque()));
        for (int i = 0; i <= cbUnid.getMaximumRowCount(); i++) {
            if (produto.getUnidade().equals(cbUnid.getItemAt(i))) {
                cbUnid.setSelectedIndex(i);
            }
        }
        
        fornecedor = fDAO.nomeFornecedor(tbProdutos.getValueAt(tbProdutos.getSelectedRow(), 4).toString());
        
        cbFornecedor.removeAllItems();
        cbFornecedor.getModel().setSelectedItem(fornecedor);
        
//        for (int i = 0; i <= cbFornecedor.getMaximumRowCount(); i++) {
//            String forne = produto.getFornecedores().getId() + " - " + produto.getFornecedores().getNome();
//            System.out.println("fornecedor: " + forne + cbFornecedor.getMaximumRowCount());
//            if (forne.equals(String.valueOf(cbFornecedor.getItemAt(i)))) {
////                cbFornecedor.removeAllItems();
//                cbFornecedor.setSelectedIndex(i);
//                System.out.println(i + " " + cbFornecedor.getItemAt(i));
//            }
//        }
        tfPrecoCompra.setText(String.valueOf(produto.getPrecoCompra()));
        tfLucroPercen.setText(String.valueOf(produto.getLucroPercen()));
        tfLucroReal.setText(String.valueOf(produto.getLucroReal()));
        tfPrecoVenda.setText(String.valueOf(produto.getPrecoVenda()));
    }//GEN-LAST:event_tbProdutosMouseClicked

    private void tfProdutoPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProdutoPesquisaKeyReleased
        // TODO add your handling code here:

        ProdutosDAO dao = new ProdutosDAO();
        String pesquisa = "'%" + tfProdutoPesquisa.getText() + "%'";
        DecimalFormat df = new DecimalFormat("0.00");
        List<Produtos> lista = dao.PesquisarProdutos(cbItemPesquisa.getSelectedItem().toString(), pesquisa);

        DefaultTableModel dados = (DefaultTableModel) tbProdutos.getModel();
        dados.setNumRows(0);
        for (Produtos c : lista) {
            String venda = df.format(c.getPrecoVenda());
            String estoque = c.getEstoque() + " " + c.getUnidade();
            String pVenda = "R$ " + venda.replaceAll("\\.", ",");
            dados.addRow(new Object[]{
                c.getCodBarras(),
                c.getDescricao(),
                pVenda,
                estoque,
                c.getFornecedores().getNome()
            });
        }
    }//GEN-LAST:event_tfProdutoPesquisaKeyReleased

    private void tfProdutoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProdutoPesquisaKeyPressed
        // TODO add your handling code here:

        //        ClientesDAO dao = new ClientesDAO();
        //        System.out.println("tipo: " + cbItemPesquisa.getSelectedItem().toString());
        //        String pesquisa = "'%" + tfClientePesquisa.getText() + "%'";
        //        List<Clientes> lista = dao.PesquisarClientes(cbItemPesquisa.getSelectedItem().toString(), pesquisa);
        //
        //        DefaultTableModel dados = (DefaultTableModel) tbClientes.getModel();
        //        dados.setNumRows(0);
        //       if (lista != null) {
        //            for (Clientes c : lista) {
        //                dados.addRow(new Object[]{
        //                    c.getId(),
        //                    c.getNome(),
        //                    c.getCelular(),
        //                    c.getPessoa(),
        //                    c.getCpfcnpj()
        //                });
        //            }
        //        }
    }//GEN-LAST:event_tfProdutoPesquisaKeyPressed

    private void tfProdutoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProdutoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProdutoPesquisaActionPerformed

    private void cbItemPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemPesquisaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbItemPesquisaItemStateChanged

    private void tfLucroRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLucroRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLucroRealActionPerformed

    private void cbFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFornecedorAncestorAdded
        // TODO add your handling code here:
        atualizarListaFornecedores();
    }//GEN-LAST:event_cbFornecedorAncestorAdded

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Produtos produtos = new Produtos();
        produtos.setCodBarras(tfCodBarras.getText());
        System.out.println("barras: " + tfCodBarras.getText());
        produtos.setDescricao(tfDescricao.getText());
        float estoque;
        estoque = Float.parseFloat(tfAddEstoque.getText().replaceAll(",", "."));
        produtos.setEstoque(estoque);
        produtos.setUnidade(cbUnid.getSelectedItem().toString());
        produtos.setPrecoCompra(Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", ".")));
        produtos.setLucroPercen(Float.parseFloat(tfLucroPercen.getText().replaceAll(",", ".")));
        produtos.setLucroReal(Double.parseDouble(tfLucroReal.getText().replaceAll(",", ".")));
        produtos.setPrecoVenda(Double.parseDouble(tfPrecoVenda.getText().replaceAll(",", ".")));
        if (tfNcm.getText().equals("")) {
            produtos.setNcm(0);
        } else {
            produtos.setNcm(Integer.parseInt(tfNcm.getText()));
        }
//        produtos.setIpi(Integer.parseInt(tfIpi.getText()));
//        produtos.setIcms(Integer.parseInt(tfIcms.getText()));
//        produtos.setFrete(Float.parseFloat(tfFrete.getText().replaceAll(",", ".")));
//        produtos.setPrecoPromo(Double.parseDouble(tfPrecoPromo.getText().replaceAll(",", ".")));
//        produtos.setFrete(Float.parseFloat(tfPercPromo.getText().replaceAll(",", ".")));
//        produtos.setValidadePromo(tfValidadePromo.getText());

        Fornecedores fornecedores = new Fornecedores();
        fornecedores = (Fornecedores) cbFornecedor.getSelectedItem();
        produtos.setFornecedores(fornecedores);

        ProdutosDAO dao = new ProdutosDAO();
        dao.cadastrarProduto(produtos);

        listTable();
        new util.Util().LimpaTela(cadProdutos1);
        new util.Util().LimpaTela(cadProdutos2);
        new util.Util().LimpaTela(cadProdutos3);

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfLucroPercenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLucroPercenKeyReleased
        // TODO add your handling code here:
        double venda;
        DecimalFormat df = new DecimalFormat("0.00");

        venda = Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", "."))
                * (1 + (Double.parseDouble(tfLucroPercen.getText().replaceAll(",", "."))) / 100);
        tfPrecoVenda.setText(String.valueOf(df.format(venda)).replaceAll("\\.", ","));
        tfLucroReal.setText(String.valueOf(df.format(
                venda - Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", ".")))
        ).replaceAll("\\.", ","));

    }//GEN-LAST:event_tfLucroPercenKeyReleased

    private void tfLucroRealKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLucroRealKeyReleased
        // TODO add your handling code here:
        double venda;
        DecimalFormat df = new DecimalFormat("0.00");

        venda = Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", "."))
                + (Double.parseDouble(tfLucroReal.getText().replaceAll(",", ".")));

        tfPrecoVenda.setText(String.valueOf(df.format(venda)).replaceAll("\\.", ","));

        tfLucroPercen.setText(String.valueOf(df.format(
                ((Double.parseDouble(tfPrecoVenda.getText().replaceAll(",", "."))
                / Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", "."))) - 1) * 100)));
    }//GEN-LAST:event_tfLucroRealKeyReleased

    private void tfPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoVendaKeyReleased
        // TODO add your handling code here:
        double venda;
        DecimalFormat df = new DecimalFormat("0.00");

        tfLucroPercen.setText(String.valueOf(df.format(
                ((Double.parseDouble(tfPrecoVenda.getText().replaceAll(",", "."))
                / Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", "."))) - 1) * 100)));
        tfLucroReal.setText(String.valueOf(df.format(
                Double.parseDouble(tfPrecoVenda.getText().replaceAll(",", "."))
                - Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", ".")))
        ).replaceAll("\\.", ","));

    }//GEN-LAST:event_tfPrecoVendaKeyReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        listTable();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Produtos produtos = new Produtos();
        produtos.setId(Integer.parseInt(tfCodInterno.getText()));
        produtos.setCodBarras(tfCodBarras.getText());
        produtos.setDescricao(tfDescricao.getText());
        float estoque;
        if (!tfEstoqueAtual.getText().equals("")) {
            if (!tfAddEstoque.getText().equals("")) {
                estoque = Float.parseFloat(tfEstoqueAtual.getText().replaceAll(",", "."))
                        + Float.parseFloat(tfAddEstoque.getText().replaceAll(",", "."));
            } else {
                estoque = Float.parseFloat(tfEstoqueAtual.getText().replaceAll(",", "."));
            }

        } else {
            estoque = Float.parseFloat(tfAddEstoque.getText().replaceAll(",", "."));
        }

        produtos.setEstoque(estoque);
        produtos.setUnidade(cbUnid.getSelectedItem().toString());
        produtos.setPrecoCompra(Double.parseDouble(tfPrecoCompra.getText().replaceAll(",", ".")));
        produtos.setLucroPercen(Float.parseFloat(tfLucroPercen.getText().replaceAll(",", ".")));
        produtos.setLucroReal(Double.parseDouble(tfLucroReal.getText().replaceAll(",", ".")));
        produtos.setPrecoVenda(Double.parseDouble(tfPrecoVenda.getText().replaceAll(",", ".")));
        if (tfNcm.getText().equals("")) {
            produtos.setNcm(0);
        } else {
            produtos.setNcm(Integer.parseInt(tfNcm.getText()));
        }
//        produtos.setIpi(Integer.parseInt(tfIpi.getText()));
//        produtos.setIcms(Integer.parseInt(tfIcms.getText()));
//        produtos.setFrete(Float.parseFloat(tfFrete.getText().replaceAll(",", ".")));
//        produtos.setPrecoPromo(Double.parseDouble(tfPrecoPromo.getText().replaceAll(",", ".")));
//        produtos.setFrete(Float.parseFloat(tfPercPromo.getText().replaceAll(",", ".")));
//        produtos.setValidadePromo(tfValidadePromo.getText());

        Fornecedores fornecedores = new Fornecedores();
        fornecedores = (Fornecedores) cbFornecedor.getSelectedItem();
        produtos.setFornecedores(fornecedores);

        ProdutosDAO dao = new ProdutosDAO();
        dao.editarProduto(produtos);
        listTable();
        new util.Util().LimpaTela(cadProdutos1);
        new util.Util().LimpaTela(cadProdutos2);
        new util.Util().LimpaTela(cadProdutos3);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        Produtos produtos = new Produtos();
        produtos.setId(Integer.parseInt(tfCodInterno.getText()));

        ProdutosDAO dao = new ProdutosDAO();
        dao.excluirProduto(produtos);
        listTable();
        new util.Util().LimpaTela(cadProdutos1);
        new util.Util().LimpaTela(cadProdutos2);
        new util.Util().LimpaTela(cadProdutos3);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:

        listTable();
        new util.Util().LimpaTela(cadProdutos1);
        new util.Util().LimpaTela(cadProdutos2);
        new util.Util().LimpaTela(cadProdutos3);
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel cadProdutos1;
    private javax.swing.JPanel cadProdutos2;
    private javax.swing.JPanel cadProdutos3;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JComboBox<String> cbItemPesquisa;
    private javax.swing.JComboBox<String> cbUnid;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JFormattedTextField tfAddEstoque;
    private javax.swing.JTextField tfCodBarras;
    private javax.swing.JTextField tfCodInterno;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfEstoqueAtual;
    private javax.swing.JTextField tfFrete;
    private javax.swing.JTextField tfIcms;
    private javax.swing.JTextField tfIpi;
    private javax.swing.JTextField tfLucroPercen;
    private javax.swing.JTextField tfLucroReal;
    private javax.swing.JTextField tfNcm;
    private javax.swing.JTextField tfPercPromo;
    private javax.swing.JTextField tfPrecoCompra;
    private javax.swing.JTextField tfPrecoPromo;
    private javax.swing.JTextField tfPrecoVenda;
    private javax.swing.JTextField tfProdutoPesquisa;
    private javax.swing.JFormattedTextField tfValidadePromo;
    private javax.swing.JTextField tfValorPromo;
    // End of variables declaration//GEN-END:variables
}
